### ISSUE TITLE
백틱으로 className 명시할 때 특정 상황에서 플러그인 에러 발생

### ISSUE THREAD

**Issue by Hongjw030** [ony3000/prettier-plugin-classnames#27]
## Dependency information

```json
  "devDependencies": {
    "@prettier/sync": "^0.5.0",
    "@types/node": "^20",
    "@types/react": "^18.2.48",
    "@types/react-datepicker": "^4.19.5",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "eslint": "^8",
    "eslint-config-next": "14.1.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-prettier": "^5.1.3",
    "postcss": "^8",
    "prettier": "^3.2.4",
    "prettier-plugin-classnames": "^0.4.0",
    "tailwindcss": "^3.3.0",
    "typescript": "^5"
  }
```

`./prettier` 파일

```json
{
	"printWidth": 80,
	"tabWidth": 2,
	"singleQuote": true,
	"semi": true,
	"useTabs": false,
	"quoteProps": "as-needed",
	"bracketSameLine": true,
   "plugins": ["prettier-plugin-classnames"]
}

```

## Steps to reproduce

동적 클래스명을 사용하기 위해 백틱으로 class name을 작성할 때, 특정 상황에서 에러가 발생합니다. 
다른 상황에선 다 괜찮은데, 백틱으로 감싼 문자열 끝이 공백일 경우 에러가 납니다.
백틱 문자열 뒤 공백을 제거하면 에러가 사라집니다. 

```ts
/*
에러 발생 1. 
            className={`${key ? `relative ` : ``}
            tablet:static`}>{key}</div>

에러 발생 2.  
            className={`${key ? `relative` : ` `}
            tablet:static`}>{key}</div>

에러 해결법  
            className={`${key ? `relative` : ` `} tablet:static`}>{key}</div>
*/
export default function Test() {
  return (
    <div>
      {[0, 1, 2, 3].map((key) => {
        return (
          <div
            key={key}
            className={`${key ? `relative ` : ``}
            tablet:static`}>{key}</div>
        );
      })}
    </div>
  );
}

```

에러 메세지 전문
```
["INFO" - 5:03:30 PM] Formatting file:///c%3A/Users/src/pages/test/index.tsx
["INFO" - 5:03:30 PM] Using config file at 'c:\Users\.prettierrc'
["INFO" - 5:03:30 PM] PrettierInstance:
{
  "modulePath": "c:\\Users\\node_modules\\prettier\\index.cjs",
  "importResolver": {},
  "callMethodResolvers": {},
  "currentCallMethodId": 55,
  "version": "3.2.4"
}
["INFO" - 5:03:30 PM] Using ignore file (if present) at c:\Users\.prettierignore
["INFO" - 5:03:30 PM] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}
["INFO" - 5:03:30 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 5:03:30 PM] Prettier Options:
{
  "filepath": "c:\\Users\\src\\pages\\test\\index.tsx",
  "parser": "typescript",
  "printWidth": 80,
  "tabWidth": 2,
  "singleQuote": true,
  "semi": true,
  "useTabs": false,
  "quoteProps": "as-needed",
  "bracketSameLine": true,
  "plugins": [
    "c:\\Users\\node_modules\\prettier-plugin-classnames\\dist\\index.js"
  ]
}
["ERROR" - 5:03:30 PM] Error formatting document.
["ERROR" - 5:03:30 PM] Unterminated template literal. (16:1)
  14 |   );
  15 | }
> 16 |
     | ^
  14 | }
  15 |
SyntaxError: Unterminated template literal. (16:1)
  14 |   );
  15 | }
> 16 |
     | ^
  14 | }
  15 |
    at Kq (file:///c:/Users/node_modules/prettier/plugins/typescript.mjs:23:498)
    at xz (file:///c:/Users/node_modules/prettier/plugins/typescript.mjs:25:794)
    at Object.Cz [as parse] (file:///c:/Users/node_modules/prettier/plugins/typescript.mjs:25:1194)
    at parse4 (file:///c:/Users/node_modules/prettier/index.mjs:22110:24)
    at async coreFormat (file:///c:/Users/node_modules/prettier/index.mjs:22600:7)
    at async formatWithCursor (file:///c:/Users/node_modules/prettier/index.mjs:22802:14)
    at async Module.format2 (file:///c:/Users/node_modules/prettier/index.mjs:24192:25)
    at async Object.parse (c:\Users\node_modules\prettier-plugin-classnames\dist\index.js:2:1858)
    at async parse4 (file:///c:/Users/node_modules/prettier/index.mjs:22110:11)
    at async coreFormat (file:///c:/Users/node_modules/prettier/index.mjs:22600:7)
["INFO" - 5:03:30 PM] Formatting completed in 51ms.
```

**Comment by ony3000** [comment]
제보 감사합니다!

플러그인 내부에서 이중 포맷팅을 하는데, 두 번째 포맷팅에서 에러가 발생하면 실제 코드(=포맷팅 전)와 에러 메시지(=중간 단계의 코드)가 일치하지 않는 불편함이 있네요. 이 부분도 같이 살펴봐야겠습니다. :sweat:

**Comment by Hongjw030** [comment]
확인 감사합니다!!
개발자님 덕분에 저도 좋은 플러그인 잘 쓰고 있습니다, 감사합니다~!! 👏👏🙏🙏

**Comment by ony3000** [comment]
@Hongjw030 수정사항이 `v0.5.2`로 배포되었습니다! :smile:
